### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [ndecker/fritzbox_exporter#15]
followed instructions: https://github.com/ndecker/fritzbox_exporter#building
but received error before using
```
 △ github.com/ndecker/fritzbox_exporter @ raspberrypi ./fritzbox_exporter -h                                                                                      master :: 784d :: ⬢
Usage of ./fritzbox_exporter:
  -gateway-address string
        The hostname or IP of the FRITZ!Box (default "fritz.box")
  -gateway-port int
        The port of the FRITZ!Box UPnP service (default 49000)
  -listen-address string
        The address to listen on for HTTP requests. (default ":9133")
  -test
        print all available metrics to stdout

 △ github.com/ndecker/fritzbox_exporter @ raspberrypi ./fritzbox_exporter -test                                                                                   master :: 784d :: ⬢
panic: EOF

goroutine 1 [running]:
panic(0x2d94e0, 0x10726058)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
main.test()
        /root/go/src/github.com/ndecker/fritzbox_exporter/main.go:285 +0xa8
main.main()
        /root/go/src/github.com/ndecker/fritzbox_exporter/main.go:312 +0x2c
```

**Comment by hausschwein** [comment]
I had the same issue. Are there any hints to solve this problem?
