### ISSUE TITLE
Crashes at start: 606 - Action Not Authorized

### ISSUE THREAD

**Issue by chevdor** [ndecker/fritzbox_exporter#21]
I am using the latest published docker version and a 6660 (cable).
From the logs, it seems that the connection is properly established but it breaks right after.

```
LOG LEVEL READ FROM CONFIG
2021-09-02 20:11:10,168     INFO fritzexporter | registering 192.168.178.1 to collector
2021-09-02 20:11:10,984     INFO fritzexporter.fritzdevice | Connection to 192.168.178.1 successful, reading capabilities
2021-09-02 20:11:10,984    DEBUG fritzexporter.fritzcapability | Capability DeviceInfo set to {self.present} on device {device.host}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/fritzexporter/__main__.py", line 74, in <module>
    main()
  File "/app/fritzexporter/__main__.py", line 58, in main
    FritzDevice(dev['hostname'], dev['username'], dev['password'], dev['name']))
  File "/app/fritzexporter/fritzdevice.py", line 35, in __init__
    self.capabilities = FritzCapabilities(self)
  File "/app/fritzexporter/fritzcapabilities.py", line 75, in __init__
    self.checkPresent(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 99, in checkPresent
    self.capabilities[c].checkCapability(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 46, in checkCapability
    device.fc.call_action(svc, action)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/fritzconnection.py", line 227, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 238, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 222, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 147, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzSecurityError: UPnPError: 
errorCode: 606
errorDescription: Action Not Authorized
```

**Comment by chevdor** [comment]
wrong repo :)
